# Builds addons/glory_voice/bin/GloryVoice.aar from this folder, without Gradle.
#
# Why no Gradle: an AAR is a zip of AndroidManifest.xml + classes.jar (+ R.txt, proguard.txt).
# The app's own Gradle build ("Use Gradle Build" in the Android preset) dexes classes.jar,
# so plain javac against android.jar + Godot's classes is all this step needs, and
# rebuilding the plugin never downloads anything.
#
# Step 1 is a desktop self-test: the pure-Java parts (codec, packetizer, jitter buffer) are
# compiled for the plain JDK and test/com/glory/voice/VoiceSelfTest runs against them.
# If it fails, no AAR is written. A broken codec only shows up on a phone as "the voice
# sounds wrong", by which point nobody can tell code from network from handset.
#
# The AAR also carries glory_voice_source.sha256, a digest of the sources it was built
# from. tools/voice_check recomputes it: editing the Java without rebuilding the
# AAR turns that check red instead of shipping a stale plugin.
#
# Every Java tool here works on copies under the (ASCII) temp dir. On a machine whose ANSI
# code page is not Chinese, Java receives non-ASCII path characters as "?" (this repo lives
# under a Chinese-named folder) and javac / jar / java reject the path. Same root cause as
# Godot's "Release Username and/or Password is invalid" when the keystore path is non-ASCII.
#
# Usage (from the repo root):
#   powershell -NoProfile -ExecutionPolicy Bypass -File android_plugins/glory_voice/build_aar.ps1
#
# Keep this file ASCII-only: Windows PowerShell 5.1 reads BOM-less files as ANSI.

[CmdletBinding()]
param(
    [string]$JdkBin = "",
    [string]$AndroidSdk = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$here = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($here)) { $here = Split-Path -Parent $MyInvocation.MyCommand.Path }
$root = [IO.Path]::GetFullPath((Join-Path $here "..\.."))

if ([string]::IsNullOrWhiteSpace($JdkBin)) {
    if (-not [string]::IsNullOrWhiteSpace($env:JAVA_HOME)) { $JdkBin = Join-Path $env:JAVA_HOME "bin" }
    else { $JdkBin = "C:\Program Files\app\JDK17\bin" }
}
if ([string]::IsNullOrWhiteSpace($AndroidSdk)) {
    if (-not [string]::IsNullOrWhiteSpace($env:ANDROID_HOME)) { $AndroidSdk = $env:ANDROID_HOME }
    else { $AndroidSdk = Join-Path $env:LOCALAPPDATA "Android\Sdk" }
}
$javac = Join-Path $JdkBin "javac.exe"
$jarTool = Join-Path $JdkBin "jar.exe"
$java = Join-Path $JdkBin "java.exe"
foreach ($tool in @($javac, $jarTool, $java)) {
    if (-not (Test-Path -LiteralPath $tool)) { throw "missing $tool (pass -JdkBin <jdk>\bin)" }
}

# Newest installed platform. The plugin guards every API above minSdk 24 with SDK_INT checks.
$androidJar = $null
foreach ($dir in (Get-ChildItem (Join-Path $AndroidSdk "platforms") -Directory | Sort-Object Name -Descending)) {
    $candidate = Join-Path $dir.FullName "android.jar"
    if (Test-Path -LiteralPath $candidate) { $androidJar = $candidate; break }
}
if ($null -eq $androidJar) { throw "no android.jar under $AndroidSdk\platforms (pass -AndroidSdk)" }

# Godot's Java API comes from the installed Android build template. android/ is gitignored and
# regenerated by the editor (Project > Install Android Build Template).
$godotAar = Join-Path $root "android\build\libs\release\godot-lib.template_release.aar"
if (-not (Test-Path -LiteralPath $godotAar)) { throw "missing $godotAar - install the Android build template first" }

$work = Join-Path ([IO.Path]::GetTempPath()) "glory_voice_aar_build"
if (Test-Path -LiteralPath $work) { Remove-Item -LiteralPath $work -Recurse -Force }
$classesDir = Join-Path $work "classes"
New-Item -ItemType Directory -Force -Path $classesDir | Out-Null

Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

$srcRoot = Join-Path $here "src"
$testRoot = Join-Path $here "test"
if (@(Get-ChildItem $srcRoot -Recurse -Filter "*.java").Count -eq 0) { throw "no .java files under $srcRoot" }
$srcCopy = Join-Path $work "src"
Copy-Item -LiteralPath $srcRoot -Destination $srcCopy -Recurse
$testCopy = Join-Path $work "test"
Copy-Item -LiteralPath $testRoot -Destination $testCopy -Recurse

# --- 1. desktop self-test --------------------------------------------------------------
# Only the classes without android.* imports: they compile and run on the plain JDK.
$pureNames = @("AdpcmCodec.java", "FrameCodec.java", "VoicePacket.java", "Resampler.java", "Packetizer.java", "RemoteStream.java")
$selfTestSources = @()
foreach ($name in $pureNames) {
    $path = Join-Path $srcCopy ("com\glory\voice\" + $name)
    if (-not (Test-Path -LiteralPath $path)) { throw "missing pure source $name" }
    $selfTestSources += $path
}
$selfTestSources += @(Get-ChildItem $testCopy -Recurse -Filter "*.java" | ForEach-Object { $_.FullName })
$selfTestOut = Join-Path $work "selftest"
New-Item -ItemType Directory -Force -Path $selfTestOut | Out-Null
& $javac -encoding UTF-8 -d $selfTestOut @selfTestSources
if ($LASTEXITCODE -ne 0) { throw "self-test javac failed" }
& $java -cp $selfTestOut com.glory.voice.VoiceSelfTest
if ($LASTEXITCODE -ne 0) { throw "VoiceSelfTest failed - AAR not built" }

# --- 2. compile the plugin against the Android API ----------------------------------------
$godotJar = Join-Path $work "godot-classes.jar"
$lib = [IO.Compression.ZipFile]::OpenRead($godotAar)
try {
    $entry = $lib.Entries | Where-Object { $_.FullName -eq "classes.jar" } | Select-Object -First 1
    if ($null -eq $entry) { throw "classes.jar not found in $godotAar" }
    [IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $godotJar, $true)
} finally {
    $lib.Dispose()
}

$sources = @(Get-ChildItem $srcCopy -Recurse -Filter "*.java" | ForEach-Object { $_.FullName })
# -source/-target 8 with -bootclasspath android.jar compiles against the real Android API
# surface (with --release the JDK's own java.* would be used instead of Android's).
# No lambdas in the plugin: android.jar's LambdaMetafactory has no metafactory, so they fail here.
& $javac -source 8 -target 8 -bootclasspath $androidJar -classpath $godotJar -encoding UTF-8 -Xlint:-options -d $classesDir @sources
if ($LASTEXITCODE -ne 0) { throw "javac failed" }

$classesJar = Join-Path $work "classes.jar"
& $jarTool cf $classesJar -C $classesDir .
if ($LASTEXITCODE -ne 0) { throw "jar failed" }

# --- 3. package --------------------------------------------------------------------------
# Source digest: "relative/path:sha256" lines, ordinal-sorted, joined with "\n", then SHA-256.
# tools/voice_check.gd computes exactly the same thing. test/ is not part of it: the tests
# are not inside the AAR, so changing only a test does not make the AAR stale.
$rel = New-Object System.Collections.Generic.List[string]
$rel.Add("AndroidManifest.xml")
$rel.Add("proguard.txt")
foreach ($file in (Get-ChildItem $srcRoot -Recurse -Filter "*.java")) {
    $rel.Add("src/" + $file.FullName.Substring($srcRoot.Length + 1).Replace("\", "/"))
}
$relArray = $rel.ToArray()
[Array]::Sort($relArray, [StringComparer]::Ordinal)
$lines = New-Object System.Collections.Generic.List[string]
foreach ($r in $relArray) {
    $hash = (Get-FileHash -LiteralPath (Join-Path $here $r) -Algorithm SHA256).Hash.ToLowerInvariant()
    $lines.Add($r + ":" + $hash)
}
$sha = [Security.Cryptography.SHA256]::Create()
$digestBytes = $sha.ComputeHash([Text.Encoding]::UTF8.GetBytes(($lines.ToArray() -join "`n")))
$digest = ($digestBytes | ForEach-Object { $_.ToString("x2") }) -join ""

$outDir = Join-Path $root "addons\glory_voice\bin"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$aar = Join-Path $outDir "GloryVoice.aar"
if (Test-Path -LiteralPath $aar) { Remove-Item -LiteralPath $aar -Force }
$out = [IO.Compression.ZipFile]::Open($aar, [IO.Compression.ZipArchiveMode]::Create)
try {
    [IO.Compression.ZipFileExtensions]::CreateEntryFromFile($out, (Join-Path $here "AndroidManifest.xml"), "AndroidManifest.xml") | Out-Null
    [IO.Compression.ZipFileExtensions]::CreateEntryFromFile($out, $classesJar, "classes.jar") | Out-Null
    [IO.Compression.ZipFileExtensions]::CreateEntryFromFile($out, (Join-Path $here "proguard.txt"), "proguard.txt") | Out-Null
    $out.CreateEntry("R.txt") | Out-Null
    $digestEntry = $out.CreateEntry("glory_voice_source.sha256")
    $writer = New-Object IO.StreamWriter($digestEntry.Open(), (New-Object Text.UTF8Encoding($false)))
    try { $writer.Write($digest) } finally { $writer.Dispose() }
} finally {
    $out.Dispose()
}

Write-Host ("built {0} ({1:N0} bytes)" -f $aar, (Get-Item -LiteralPath $aar).Length)
Write-Host ("  android.jar: {0}" -f $androidJar)
Write-Host ("  godot lib:   {0}" -f $godotAar)
Write-Host ("  source sha:  {0}" -f $digest)
