extends RefCounted
class_name ExportPresetsTemplate

# The one definition of "what a shareable copy of export_presets.cfg looks like".
#
# Why this file exists at all: export_presets.cfg is in .gitignore, and the root
# copy has never been in git, because a Release preset stores the keystore password
# in plain text. The side effect is that A5's exclude_filter does not travel with
# the repo — a fresh clone exports with an empty filter and silently packs backups/
# into the APK. So we commit a secret-free template instead.
#
# A committed copy of a live file rots. The whole point of putting the rendering
# rule here, rather than in whoever regenerates the template, is that the generator
# and the drift check read the same rule: they cannot disagree about which fields
# are secret, and the check cannot be satisfied by a template the generator would
# not have produced.

# Values blanked in the template. Together with LOCAL_KEYS below, these are the
# only differences the drift check tolerates; everything else must match byte for
# byte.
#
# Godot writes these keys only once they have been set in the editor, so a
# keystore-free project simply has none of them — that is expected, not an error.
const SECRET_KEYS: PackedStringArray = [
	"keystore/debug",
	"keystore/debug_user",
	"keystore/debug_password",
	"keystore/release",
	"keystore/release_user",
	"keystore/release_password",
	"encryption_key",
	"script_encryption_key",
]

# Blanked for a different reason: not secret, just specific to one machine.
#
# export_path is whatever folder that developer happens to export into. It plays
# no part in a reproducible build -- tools/android_smoke.sh passes the output path
# on the command line (`--export-debug <preset> <path>`), so the preset field only
# ever affects a manual export from the editor. Comparing it made the drift check
# red on every machine except the one that last regenerated the template, which
# is exactly the kind of permanent red that teaches people to ignore a gate.
const LOCAL_KEYS: PackedStringArray = [
	"export_path",
]

const LIVE_PATH := "res://export_presets.cfg"
const TEMPLATE_PATH := "res://export_presets.template.cfg"

# Prefixed to the template. Godot's ConfigFile treats ';' as a comment, so the
# template stays directly copyable to export_presets.cfg.
const HEADER: PackedStringArray = [
	"; Generated by tools/export_presets_template.tscn — do not edit by hand.",
	";",
	"; export_presets.cfg is gitignored because a Release preset stores the keystore",
	"; password in plain text. This secret-free copy exists so that a fresh clone can",
	"; still export a correctly filtered APK: copy it to export_presets.cfg, then set",
	"; your own keystore fields in the editor.",
	";",
	"; export_path is blank here for a different reason: it is per-machine, and no",
	"; automated build reads it -- tools/android_smoke.sh passes the output path on",
	"; the command line. Set it if you export by hand from the editor.",
	";",
	"; tools/export_presets_check.tscn fails if this file and the live one have drifted",
	"; in any field other than the blanked ones above, so regenerate it whenever you",
	"; change a preset.",
]


# The template text for a given live export_presets.cfg.
static func render(source: String) -> String:
	var out: PackedStringArray = []
	for line in HEADER:
		out.append(line)
	out.append("")
	for raw_line in source.split("\n"):
		out.append(_blank_if_unshareable(str(raw_line)))
	return "\n".join(out)


# Both files reduced to what must match: header comments dropped, secret values
# blanked, trailing whitespace ignored. Comparing normalized forms is what lets
# the check be exact about everything else.
static func normalize(text: String) -> PackedStringArray:
	var out: PackedStringArray = []
	for raw_line in text.split("\n"):
		var line := str(raw_line)
		if line.begins_with(";"):
			continue
		out.append(_blank_if_unshareable(line).strip_edges(false, true))
	# Blank padding around the content is not drift: the template's comment header
	# is followed by a separator line the live file has no reason to carry, and
	# either file may or may not end with a newline.
	while not out.is_empty() and str(out[0]).is_empty():
		out.remove_at(0)
	while not out.is_empty() and str(out[out.size() - 1]).is_empty():
		out.remove_at(out.size() - 1)
	return out


# The `key=` at the start of a line, or "" if the line is not an assignment.
static func key_of(line: String) -> String:
	var at := line.find("=")
	if at <= 0:
		return ""
	return line.substr(0, at)


# Both render() and normalize() go through here, which is what keeps the generator
# and the drift check from disagreeing about which fields travel with the repo.
static func _blank_if_unshareable(line: String) -> String:
	var key := key_of(line)
	if key.is_empty():
		return line
	if not SECRET_KEYS.has(key) and not LOCAL_KEYS.has(key):
		return line
	return "%s=\"\"" % key
